#!/usr/bin/env python
# coding: utf-8

from __future__ import print_function
import sys
import io
import os
import shutil
import fileinput

# INPUT FILE
try:
    sys.argv[1]
except:
    print("\nUsage: caption-clean input-file [output file] \n")
    sys.exit(1)
else:
    inFile = sys.argv[1]

# OUTPUT FILE [optional]
try:
    sys.argv[2]
except:
    # create a backup file
    backupFile = os.getcwd() + "/" + inFile + ".orig"
    shutil.copyfile(inFile, backupFile)
    outFile = inFile
else:
    outFile = sys.argv[2]

# make sure there are only two args or less
try:
    sys.argv[3]
except:
    pass # We only want a max of two args
else:
    print("Error: too many arguments passed.")
    print("Usage: caption-clean input-file [output file]")
    sys.exit(1)

# Search and replace some chars that Merlin/COVE do not like.

readOriginal = open(inFile, 'rb')
middleFile = open(inFile + ".tmp",'w')

for line in readOriginal:
    line = line.replace('«', '[')
    line = line.replace('»', ']')
    line = line.replace('♩', '[music]')
    line = line.replace('♪', '[music]')
    line = line.replace('♫', '[music]')
    line = line.replace('♫', '[music]')
    line = line.replace(' pp', ' ')
    line = line.replace(' PP', ' ')
    middleFile.write(line + "\n")

middleFile.close()
readOriginal.close()

########################################################################
# Eperimenting with conversion to UTF-8. Although after trying a few
# ingests, it appears this is taken care of when the file is uploaded.
# For now I am leaving the code below to experiment with later if needed.
########################################################################

# Convert the entire file to UTF8. Non UTF8 chars will be replaced with
# the closest matching/similar char.
#myFile = open(inFile + ".tmp", 'rb')
#content = unicode(myFile.read())
#myFile.close()
#myFile = open(outFile, 'wb')
#myFile.write(content.encode('utf-8'))
#myFile.close()

#with io.open(middleFile,'r',encoding='utf-8',errors='ignore') as dirtyFile, \
#     io.open(outFile,'w',encoding='ascii',errors='ignore') as cleanFile:
#
#     for line in dirtyFile:
#         print(*line.split(), file=cleanFile)
